### ISSUE TITLE
[Feature request] Add name alias

### ISSUE THREAD

**Issue by Zelaf** [Erallie/voicely-text#2]
**Is your feature request related to a problem? Please describe.**
Currently the bot says the users full name, including underscores and other special characters. It adds a lot of extra time before the "says" and the actual text message is spoken.

**Describe the solution you'd like**
Add a command option to set a name alias, so for example if my name in a server would be "Zelaf Ary" I could set my name alias to just "Zelaf".

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Erallie** [comment]
I think this is a good idea! I will add this as a feature when I have time!

**Comment by Erallie** [comment]
@Zelaf Hey! I implemented this! You can have a nickname set by default and an override for specific servers! Please feel free to test it out, and let me know if it's good so I can close the issue!

**Comment by Erallie** [comment]
Actually, I will close this issue, since I considered it done. @Zelaf if you need anything else regarding this, comment on this issue again, and I will reopen it. Otherwise, create a new issue. Thank you for requesting this, since it's a really good idea!
